#!/usr/bin/env python3

# SPDX-License-Identifier: BUSL-1.1
# Copyright 2026 Ryan Gillespie / Optitransfer
#
# Licensed under the Business Source License 1.1 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/mgillr/crdt-merge/blob/main/LICENSE
#
# Change Date: 2028-03-29
# Change License: Apache License, Version 2.0

"""Property-based CRDT law tests using Hypothesis.

Tests commutativity, idempotency, and associativity of model merge strategies
using randomised inputs generated by Hypothesis.

Run with:
    pip install hypothesis numpy
    pytest tests/test_crdt_properties.py -v
"""
import sys
import os

# Ensure the package is importable
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import numpy as np
import pytest

try:
    from hypothesis import given, settings, HealthCheck
    from hypothesis import strategies as st
    from hypothesis.extra.numpy import arrays

    HAS_HYPOTHESIS = True
except ImportError:
    HAS_HYPOTHESIS = False

from crdt_merge.model.strategies import get_strategy, list_strategies
from crdt_merge.model.strategies.base import CRDTTier

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

TENSOR_DIM = 8
ABS_TOL = 1e-6

# Strategies that require base=
BASE_REQUIRED = {
    "task_arithmetic", "ties", "dare", "della", "dare_ties",
    "model_breadcrumbs", "emr", "star", "svd_knot_tying",
    "adarank", "negative_merge", "split_unlearn_merge", "safe_merge",
}

# Strategies with stochastic behaviour (skip determinism tests)
STOCHASTIC = {"dare", "della", "dare_ties", "evolutionary_merge", "genetic_merge"}

# Strategies that declare commutativity
COMMUTATIVE_STRATEGIES = []
IDEMPOTENT_STRATEGIES = []

for name in list_strategies():
    s = get_strategy(name)
    props = s.crdt_properties
    if props.get("commutative") is True:
        COMMUTATIVE_STRATEGIES.append(name)
    if props.get("idempotent") is True:
        IDEMPOTENT_STRATEGIES.append(name)

def _approx_equal(a, b, tol=ABS_TOL):
    """Element-wise approximate equality."""
    a_arr = np.asarray(a, dtype=float).ravel()
    b_arr = np.asarray(b, dtype=float).ravel()
    if a_arr.shape != b_arr.shape:
        return False
    return np.allclose(a_arr, b_arr, atol=tol, rtol=0)

def _make_tensor(seed, dim=TENSOR_DIM):
    rng = np.random.RandomState(seed)
    return rng.randn(dim).tolist()

# ---------------------------------------------------------------------------
# Hypothesis strategies
# ---------------------------------------------------------------------------

tensor_strategy = st.integers(min_value=0, max_value=100000).map(
    lambda s: _make_tensor(s)
)

# ---------------------------------------------------------------------------
# Property-based tests
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not HAS_HYPOTHESIS, reason="hypothesis not installed")
class TestCommutativity:
    """merge(A, B) == merge(B, A) for strategies that declare commutativity."""

    @pytest.fixture(params=COMMUTATIVE_STRATEGIES)
    def strategy_name(self, request):
        return request.param

    @given(seed_a=st.integers(0, 99999), seed_b=st.integers(0, 99999))
    @settings(max_examples=50, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_commutative(self, strategy_name, seed_a, seed_b):
        s = get_strategy(strategy_name)
        a = _make_tensor(seed_a)
        b = _make_tensor(seed_b)
        base = _make_tensor(42) if strategy_name in BASE_REQUIRED else None

        kwargs = {}
        if strategy_name in BASE_REQUIRED:
            kwargs["base"] = base
        if strategy_name in STOCHASTIC:
            kwargs["seed"] = 123

        ab = s.merge([a, b], **kwargs)
        ba = s.merge([b, a], **kwargs)
        assert _approx_equal(ab, ba), (
            f"{strategy_name}: merge(A,B) != merge(B,A)"
        )

@pytest.mark.skipif(not HAS_HYPOTHESIS, reason="hypothesis not installed")
class TestIdempotency:
    """merge(A, A) == A for strategies that declare idempotency."""

    @pytest.fixture(params=IDEMPOTENT_STRATEGIES)
    def strategy_name(self, request):
        return request.param

    @given(seed_a=st.integers(0, 99999))
    @settings(max_examples=50, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_idempotent(self, strategy_name, seed_a):
        s = get_strategy(strategy_name)
        a = _make_tensor(seed_a)
        base = _make_tensor(42) if strategy_name in BASE_REQUIRED else None

        kwargs = {}
        if strategy_name in BASE_REQUIRED:
            kwargs["base"] = base
        if strategy_name in STOCHASTIC:
            kwargs["seed"] = 123

        aa = s.merge([a, a], **kwargs)
        assert _approx_equal(aa, a), (
            f"{strategy_name}: merge(A,A) != A"
        )

@pytest.mark.skipif(not HAS_HYPOTHESIS, reason="hypothesis not installed")
class TestCRDTTierConsistency:
    """Verify that crdt_tier matches crdt_properties for all strategies."""

    @pytest.fixture(params=list(list_strategies()))
    def strategy_name(self, request):
        return request.param

    def test_tier_matches_properties(self, strategy_name):
        s = get_strategy(strategy_name)
        props = s.crdt_properties
        tier = s.crdt_tier

        comm = props.get("commutative") is True
        assoc = props.get("associative") is True
        idem = props.get("idempotent") is True

        if all([comm, assoc, idem]):
            assert tier == CRDTTier.TRUE_CRDT, f"{strategy_name}: expected TRUE_CRDT"
        elif any([comm, assoc, idem]):
            assert tier == CRDTTier.PARTIAL_CRDT, f"{strategy_name}: expected PARTIAL_CRDT"
        else:
            assert tier == CRDTTier.NOT_CRDT, f"{strategy_name}: expected NOT_CRDT"

if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
