# SPDX-License-Identifier: BUSL-1.1
# Copyright 2026 Ryan Gillespie / Optitransfer
#
# Licensed under the Business Source License 1.1 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/mgillr/crdt-merge/blob/main/LICENSE
#
# Change Date: 2028-03-29
# Change License: Apache License, Version 2.0

#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# On 2028-03-29 this file converts to Apache License, Version 2.0.

"""
dbt Package Generator — generate cross-database dbt macros for CRDT merge.

Produces Jinja-templated SQL macros that implement CRDT merge strategies
(LWW, Max, Min, Union, Concat, Priority) across Snowflake, BigQuery,
Postgres, and DuckDB.  Users add the generated macros to their dbt project
and call them from models.

Usage::

    from crdt_merge.accelerators.dbt_package import DbtMergeGenerator

    gen = DbtMergeGenerator()
    sql = gen.generate_macro(
        sources=["stg_east", "stg_west"],
        key="customer_id",
        strategies={"name": "lww", "revenue": "max"},
    )
    yaml = gen.generate_packages_yml()

All external dependencies are lazy-imported.
"""

from __future__ import annotations

__status__ = 'stub'

import warnings
warnings.warn(
    "crdt_merge.accelerators.dbt_package is not yet implemented (stub)",
    UserWarning,
    stacklevel=2,
)

import textwrap
import types
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence, Tuple

from crdt_merge.accelerators import register_accelerator

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_SUPPORTED_WAREHOUSES = ("snowflake", "bigquery", "postgres", "duckdb")

# Issue #20: Immutable mapping — strategy names are a fixed lookup table.
# Using MappingProxyType prevents accidental mutation in multi-threaded contexts.
_STRATEGY_MAP = types.MappingProxyType({
    "lww": "lww",
    "max": "max",
    "maxwins": "max",
    "min": "min",
    "minwins": "min",
    "union": "union",
    "unionset": "union",
    "concat": "concat",
    "priority": "priority",
    "longest": "longest",
    "longestwins": "longest",
})

_VERSION = "0.7.0"

# ---------------------------------------------------------------------------
# Jinja macro templates (cross-database)
# ---------------------------------------------------------------------------

_MACRO_HEADER = textwrap.dedent("""\
    {#-- crdt_merge dbt macro — generated by crdt_merge v%s --#}
    {#-- Strategy reference:
         lww      — last-writer-wins (latest _merged_at wins)
         max      — higher numeric value wins
         min      — lower numeric value wins
         union    — comma-separated set union
         concat   — concatenate with separator
         priority — first match in ordered list wins
         longest  — longer string wins
    --#}
""") % _VERSION

_RESOLVE_LWW = textwrap.dedent("""\
    {%%- macro crdt_resolve_lww(col, ts_col, sources) -%%}
      case
      {%%- for src in sources %%}
        when {{ src }}.{{ ts_col }} = __crdt_max_ts.max_ts
          then {{ src }}.{{ col }}
      {%%- endfor %%}
      end as {{ col }}
    {%%- endmacro -%%}
""")

_RESOLVE_MAX = textwrap.dedent("""\
    {%%- macro crdt_resolve_max(col, sources) -%%}
      greatest(
        {%%- for src in sources %%}
        {{ src }}.{{ col }}{%% if not loop.last %%},{%% endif %%}
        {%%- endfor %%}
      ) as {{ col }}
    {%%- endmacro -%%}
""")

_RESOLVE_MIN = textwrap.dedent("""\
    {%%- macro crdt_resolve_min(col, sources) -%%}
      least(
        {%%- for src in sources %%}
        {{ src }}.{{ col }}{%% if not loop.last %%},{%% endif %%}
        {%%- endfor %%}
      ) as {{ col }}
    {%%- endmacro -%%}
""")

_RESOLVE_UNION = textwrap.dedent("""\
    {%%- macro crdt_resolve_union(col, sources, separator=',') -%%}
    {#-- Set-union of comma-delimited values (warehouse-portable) --#}
      {%%- if target.type == 'bigquery' -%%}
        array_to_string(array(
          select distinct val from unnest(
            split(concat_ws({{ separator }},
              {%%- for src in sources %%}
              coalesce({{ src }}.{{ col }}, ''){%% if not loop.last %%},{%% endif %%}
              {%%- endfor %%}
            ), {{ separator }})
          ) as val
        ), {{ separator }}) as {{ col }}
      {%%- else -%%}
        (select string_agg(distinct val, {{ separator }})
         from unnest(string_to_array(
           concat_ws({{ separator }},
             {%%- for src in sources %%}
             coalesce({{ src }}.{{ col }}, ''){%% if not loop.last %%},{%% endif %%}
             {%%- endfor %%}
           ), {{ separator }})
         ) as val
        ) as {{ col }}
      {%%- endif -%%}
    {%%- endmacro -%%}
""")

_RESOLVE_CONCAT = textwrap.dedent("""\
    {%%- macro crdt_resolve_concat(col, sources, separator=' | ') -%%}
      concat_ws({{ separator }},
        {%%- for src in sources %%}
        {{ src }}.{{ col }}{%% if not loop.last %%},{%% endif %%}
        {%%- endfor %%}
      ) as {{ col }}
    {%%- endmacro -%%}
""")

_RESOLVE_LONGEST = textwrap.dedent("""\
    {%%- macro crdt_resolve_longest(col, sources) -%%}
      case
      {%%- for src in sources %%}
        when length(coalesce({{ src }}.{{ col }}, '')) >= coalesce(
          {%%- for other in sources %%}
          {%%- if other != src %%}
          length(coalesce({{ other }}.{{ col }}, '')),
          {%%- endif %%}
          {%%- endfor %%}
          0)
        then {{ src }}.{{ col }}
      {%%- endfor %%}
      end as {{ col }}
    {%%- endmacro -%%}
""")

_RESOLVE_PRIORITY = textwrap.dedent("""\
    {%%- macro crdt_resolve_priority(col, sources, priority_list) -%%}
    {#-- First match in priority_list wins (highest priority = index 0) --#}
      case
      {%%- for pval in priority_list %%}
        {%%- for src in sources %%}
        when {{ src }}.{{ col }} = '{{ pval }}' then '{{ pval }}'
        {%%- endfor %%}
      {%%- endfor %%}
        else coalesce(
          {%%- for src in sources %%}
          {{ src }}.{{ col }}{%% if not loop.last %%},{%% endif %%}
          {%%- endfor %%}
        )
      end as {{ col }}
    {%%- endmacro -%%}
""")

# ---------------------------------------------------------------------------
# Pre-built model templates
# ---------------------------------------------------------------------------

_MODEL_MERGE_TEMPLATE = textwrap.dedent("""\
    {{#-- crdt_merge model: %(model_name)s --#}}
    {{-- Generated by crdt_merge dbt package v%(version)s --}}

    {{{{ config(materialized='%(materialization)s') }}}}

    with %(cte_block)s

    __crdt_max_ts as (
        select
            %(key)s,
            greatest(%(ts_cols)s) as max_ts
        from %(first_source)s
        %(join_block)s
    )

    select
        %(first_source)s.%(key)s,
        %(select_cols)s
    from %(first_source)s
    %(join_block)s
    join __crdt_max_ts on %(first_source)s.%(key)s = __crdt_max_ts.%(key)s
""")

# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class MacroConfig:
    """Configuration for a generated dbt macro."""

    sources: List[str]
    key: str
    strategies: Dict[str, str]
    timestamp_column: str = "_merged_at"
    macro_name: Optional[str] = None
    warehouse: Optional[str] = None
    separator: str = ","
    priority_lists: Dict[str, List[str]] = field(default_factory=dict)

    def __post_init__(self) -> None:
        normalised: Dict[str, str] = {}
        for col, strat in self.strategies.items():
            key = strat.lower().replace("_", "").replace("-", "")
            if key not in _STRATEGY_MAP:
                raise ValueError(
                    f"Unknown strategy '{strat}' for column '{col}'. "
                    f"Supported: {list(_STRATEGY_MAP.keys())}"
                )
            normalised[col] = _STRATEGY_MAP[key]
        self.strategies = normalised

@dataclass
class ModelConfig:
    """Configuration for a pre-built dbt model."""

    name: str
    sources: List[str]
    key: str
    strategies: Dict[str, str]
    materialization: str = "table"
    timestamp_column: str = "_merged_at"

# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

@register_accelerator
class DbtMergeGenerator:
    """Generate dbt macros and models for CRDT merge operations.

    Attributes:
        name: Accelerator name for the registry.
        version: Package version string.
    """

    name: str = "dbt_package"
    version: str = _VERSION

    def __init__(self, *, warehouse: Optional[str] = None) -> None:
        """Initialise the generator.

        Args:
            warehouse: Target warehouse hint (snowflake, bigquery, postgres,
                       duckdb). If *None* the generated macros will use Jinja
                       ``target.type`` for runtime dispatch.
        """
        if warehouse is not None and warehouse.lower() not in _SUPPORTED_WAREHOUSES:
            raise ValueError(
                f"Unsupported warehouse '{warehouse}'. "
                f"Supported: {list(_SUPPORTED_WAREHOUSES)}"
            )
        self._warehouse = warehouse.lower() if warehouse else None

    # -- AcceleratorProtocol -------------------------------------------------

    def health_check(self) -> Dict[str, Any]:
        """Return health / readiness status."""
        return {
            "name": self.name,
            "version": self.version,
            "warehouse": self._warehouse or "auto",
            "supported_warehouses": list(_SUPPORTED_WAREHOUSES),
            "status": "ok",
        }

    def is_available(self) -> bool:
        """dbt macros have no runtime dependencies — always available."""
        return True

    # -- Macro generation ----------------------------------------------------

    def generate_macro(
        self,
        sources: List[str],
        key: str,
        strategies: Dict[str, str],
        *,
        timestamp_column: str = "_merged_at",
        macro_name: Optional[str] = None,
        separator: str = ",",
        priority_lists: Optional[Dict[str, List[str]]] = None,
    ) -> str:
        """Generate a dbt Jinja macro for CRDT merge.

        Args:
            sources: List of dbt source/model references.
            key: Primary key column name.
            strategies: Mapping of column name → strategy name.
            timestamp_column: Column used for LWW timestamps.
            macro_name: Optional custom name for the generated macro.
            separator: Separator for union / concat strategies.
            priority_lists: Mapping of column → priority ordered list.

        Returns:
            A string containing the complete dbt macro.

        Raises:
            ValueError: If strategies reference unknown strategy names,
                        or if sources list is empty.
        """
        if not sources or len(sources) < 2:
            raise ValueError("At least two sources are required for merge")
        if not key:
            raise ValueError("Key column must be specified")

        cfg = MacroConfig(
            sources=sources,
            key=key,
            strategies=strategies,
            timestamp_column=timestamp_column,
            macro_name=macro_name,
            warehouse=self._warehouse,
            separator=separator,
            priority_lists=priority_lists or {},
        )
        return self._render_macro(cfg)

    def generate_resolver_macros(self) -> str:
        """Generate the full set of resolver helper macros.

        Returns:
            A string containing all resolver macros (lww, max, min, …).
        """
        parts = [_MACRO_HEADER]
        parts.append(_RESOLVE_LWW)
        parts.append(_RESOLVE_MAX)
        parts.append(_RESOLVE_MIN)
        parts.append(_RESOLVE_UNION)
        parts.append(_RESOLVE_CONCAT)
        parts.append(_RESOLVE_LONGEST)
        parts.append(_RESOLVE_PRIORITY)
        return "\n".join(parts)

    def generate_model(
        self,
        model_name: str,
        sources: List[str],
        key: str,
        strategies: Dict[str, str],
        *,
        materialization: str = "table",
        timestamp_column: str = "_merged_at",
    ) -> str:
        """Generate a pre-built dbt model SQL file.

        Args:
            model_name: Name for the model.
            sources: Source model references.
            key: Primary key column.
            strategies: Column → strategy mapping.
            materialization: dbt materialization (table, view, incremental).
            timestamp_column: Timestamp column for LWW.

        Returns:
            Complete dbt model SQL string.
        """
        if not sources or len(sources) < 2:
            raise ValueError("At least two sources are required")

        mcfg = MacroConfig(
            sources=sources,
            key=key,
            strategies=strategies,
            timestamp_column=timestamp_column,
        )

        first = sources[0]
        cte_parts: List[str] = []
        for src in sources:
            cte_parts.append(f"{src} as (select * from {{{{ ref('{src}') }}}})")
        cte_block = ",\n".join(cte_parts)

        ts_cols = ", ".join(f"{src}.{timestamp_column}" for src in sources)
        join_lines: List[str] = []
        for src in sources[1:]:
            join_lines.append(
                f"full outer join {src} on {first}.{key} = {src}.{key}"
            )
        join_block = "\n    ".join(join_lines)

        select_parts: List[str] = []
        for col, strat in mcfg.strategies.items():
            select_parts.append(self._col_expression(col, strat, sources, timestamp_column))

        select_cols = ",\n        ".join(select_parts) if select_parts else f"{first}.*"

        return _MODEL_MERGE_TEMPLATE % {
            "model_name": model_name,
            "version": _VERSION,
            "materialization": materialization,
            "cte_block": cte_block,
            "key": key,
            "ts_cols": ts_cols,
            "first_source": first,
            "join_block": join_block,
            "select_cols": select_cols,
        }

    def generate_packages_yml(
        self,
        *,
        package_name: str = "crdt_merge",
        version: Optional[str] = None,
    ) -> str:
        """Generate a dbt ``packages.yml`` snippet.

        Args:
            package_name: Name for the dbt package.
            version: Semver version string. Defaults to current version.

        Returns:
            YAML string for ``packages.yml``.
        """
        ver = version or _VERSION
        return textwrap.dedent(f"""\
            packages:
              - package: {package_name}
                version: "{ver}"
        """)

    def generate_schema_yml(
        self,
        model_name: str,
        key: str,
        strategies: Dict[str, str],
        *,
        description: Optional[str] = None,
    ) -> str:
        """Generate a dbt ``schema.yml`` entry for a merge model.

        Args:
            model_name: Name of the dbt model.
            key: Primary key column.
            strategies: Column → strategy mapping.
            description: Optional model description.

        Returns:
            YAML string for inclusion in ``schema.yml``.
        """
        desc = description or f"CRDT merge model for {model_name}"
        lines = [
            "version: 2",
            "",
            "models:",
            f"  - name: {model_name}",
            f"    description: \"{desc}\"",
            "    columns:",
            f"      - name: {key}",
            "        description: \"Primary key\"",
            "        tests:",
            "          - unique",
            "          - not_null",
        ]
        for col, strat in strategies.items():
            lines.append(f"      - name: {col}")
            lines.append(f"        description: \"Merged with {strat} strategy\"")
        return "\n".join(lines) + "\n"

    def list_supported_strategies(self) -> List[str]:
        """Return list of supported strategy names."""
        return sorted(set(_STRATEGY_MAP.values()))

    def list_supported_warehouses(self) -> List[str]:
        """Return list of supported warehouse targets."""
        return list(_SUPPORTED_WAREHOUSES)

    # -- Internal helpers ----------------------------------------------------

    def _render_macro(self, cfg: MacroConfig) -> str:
        """Render a complete merge macro from configuration."""
        name = cfg.macro_name or f"crdt_merge_{'_'.join(cfg.sources)}"
        src_args = ", ".join(cfg.sources)

        lines: List[str] = [
            _MACRO_HEADER.rstrip(),
            "",
            f"{{% macro {name}() %}}",
            "",
            f"  -- CRDT merge: {src_args} on {cfg.key}",
            f"  -- Generated by crdt_merge v{_VERSION}",
            "",
        ]

        # CTE for each source
        cte_parts: List[str] = []
        for src in cfg.sources:
            cte_parts.append(f"  {src} as (select * from {{{{ ref('{src}') }}}})")
        lines.append("  with")
        lines.append(",\n".join(cte_parts) + ",")
        lines.append("")

        # Max-timestamp CTE for LWW
        has_lww = any(s == "lww" for s in cfg.strategies.values())
        if has_lww:
            first = cfg.sources[0]
            ts_cols = ", ".join(
                f"{src}.{cfg.timestamp_column}" for src in cfg.sources
            )
            lines.append("  __crdt_max_ts as (")
            lines.append("    select")
            lines.append(f"      coalesce({', '.join(f'{s}.{cfg.key}' for s in cfg.sources)}) as {cfg.key},")
            lines.append(f"      greatest({ts_cols}) as max_ts")
            lines.append(f"    from {first}")
            for src in cfg.sources[1:]:
                lines.append(
                    f"    full outer join {src} on {first}.{cfg.key} = {src}.{cfg.key}"
                )
            lines.append("  ),")
            lines.append("")

        # Final select
        first = cfg.sources[0]
        lines.append("  __crdt_merged as (")
        lines.append("    select")
        lines.append(f"      coalesce({', '.join(f'{s}.{cfg.key}' for s in cfg.sources)}) as {cfg.key},")

        for col, strat in cfg.strategies.items():
            expr = self._col_expression(
                col, strat, cfg.sources, cfg.timestamp_column,
                separator=cfg.separator,
                priority_list=cfg.priority_lists.get(col),
            )
            lines.append(f"      {expr},")

        # Remove trailing comma from last column
        if lines[-1].endswith(","):
            lines[-1] = lines[-1][:-1]

        lines.append(f"    from {first}")
        for src in cfg.sources[1:]:
            lines.append(
                f"    full outer join {src} on {first}.{cfg.key} = {src}.{cfg.key}"
            )
        if has_lww:
            lines.append(
                f"    join __crdt_max_ts on coalesce({', '.join(f'{s}.{cfg.key}' for s in cfg.sources)}) = __crdt_max_ts.{cfg.key}"
            )
        lines.append("  )")
        lines.append("")
        lines.append("  select * from __crdt_merged")
        lines.append("")
        lines.append("{% endmacro %}")

        return "\n".join(lines) + "\n"

    def _col_expression(
        self,
        col: str,
        strategy: str,
        sources: List[str],
        ts_col: str,
        *,
        separator: str = ",",
        priority_list: Optional[List[str]] = None,
    ) -> str:
        """Build a SQL expression for a single column given the strategy."""
        strat = _STRATEGY_MAP.get(strategy.lower(), strategy.lower())
        src_refs = [f"{s}.{col}" for s in sources]

        if strat == "lww":
            cases = []
            for src in sources:
                cases.append(
                    f"when {src}.{ts_col} = __crdt_max_ts.max_ts then {src}.{col}"
                )
            return f"case {' '.join(cases)} end as {col}"

        elif strat == "max":
            return f"greatest({', '.join(src_refs)}) as {col}"

        elif strat == "min":
            return f"least({', '.join(src_refs)}) as {col}"

        elif strat == "union":
            inner = ", ".join(f"coalesce({r}, '')" for r in src_refs)
            return f"concat_ws('{separator}', {inner}) as {col}"

        elif strat == "concat":
            return f"concat_ws('{separator}', {', '.join(src_refs)}) as {col}"

        elif strat == "longest":
            cases = []
            for src in sources:
                others = [
                    f"length(coalesce({s}.{col}, ''))"
                    for s in sources if s != src
                ]
                others_str = ", ".join(others) if others else "0"
                cases.append(
                    f"when length(coalesce({src}.{col}, '')) >= greatest({others_str}) "
                    f"then {src}.{col}"
                )
            return f"case {' '.join(cases)} end as {col}"

        elif strat == "priority":
            plist = priority_list or []
            cases = []
            for pval in plist:
                for src in sources:
                    cases.append(f"when {src}.{col} = '{pval}' then '{pval}'")
            fallback = f"coalesce({', '.join(src_refs)})"
            return f"case {' '.join(cases)} else {fallback} end as {col}"

        else:
            # Fallback — coalesce
            return f"coalesce({', '.join(src_refs)}) as {col}"
